// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwndassuuumiyfdaowte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13bmRhc3N1dXVtaXlmZGFvd3RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwMDMzMTIsImV4cCI6MjA3OTU3OTMxMn0.NR2yWc76DLovTiMJqd290jq3VM30EUDmGyn0M0V4XSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});